backend:
  # Use netlify identity as backend
  # name: git-gateway
  # branch: master
  ### enable below lines for github integration ###
  name: github
  repo: acacia314/fallen-angels-website
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow

collections:
  - name: "players"
    label: "Players"
    folder: "src/_data/players"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", hint: "Used in the URL, e.g., /players/slug" }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Bio", name: "body", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Name, name: name, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
